services:
  site:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "4000:4000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bundle exec jekyll serve --watch --host 0.0.0.0
